contact_links:
  - name: ðŸ‘ª Yanki Forum
    url: https://forum.misskey.io/
    about: Ask questions and share knowledge
  - name: ðŸ’¬ Yanki official Discord
    url: https://discord.gg/Wp8gVStHW3
    about: Chat freely about Yanki
